{{- if and .Values.console.enabled .Values.console.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "krkn-operator.console.fullname" . }}
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.console.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.console.ingress.className }}
  ingressClassName: {{ .Values.console.ingress.className }}
  {{- end }}
  {{- $tls := .Values.console.ingress.tls }}
  {{- if or (and (kindIs "map" $tls) $tls.enabled) (and (kindIs "slice" $tls) (gt (len $tls) 0)) }}
  tls:
    {{- if kindIs "slice" $tls }}
    {{- toYaml $tls | nindent 4 }}
    {{- else }}
    - hosts:
      {{- if .Values.console.ingress.hostname }}
      - {{ .Values.console.ingress.hostname | quote }}
      {{- end }}
      secretName: {{ $tls.secretName | default (printf "%s-tls" (include "krkn-operator.console.fullname" .)) }}
    {{- end }}
  {{- end }}
  rules:
    - {{- if .Values.console.ingress.hostname }}
      host: {{ .Values.console.ingress.hostname | quote }}
      {{- end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "krkn-operator.console.fullname" . }}
              port:
                number: {{ .Values.console.service.port }}
{{- end }}
