{{- if and .Values.acm.enabled .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "krkn-operator.acm.fullname" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: acm
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - krkn.krkn-chaos.dev
  resources:
  - krknoperatortargetproviderconfigs
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krkn.krkn-chaos.dev
  resources:
  - krknoperatortargetproviderconfigs/status
  - krknoperatortargetproviders/status
  - krkntargetrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - krkn.krkn-chaos.dev
  resources:
  - krknoperatortargetproviders
  - krkntargetrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krkn.krkn-chaos.dev
  resources:
  - krkntargetrequests/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "krkn-operator.acm.fullname" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: acm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "krkn-operator.acm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "krkn-operator.acm.fullname" . }}
  namespace: {{ include "krkn-operator.namespace" . }}
{{- end }}
