{{- if .Values.acm.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krkn-operator.acm.fullname" . }}
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: acm
{{- end }}
