apiVersion: v1
kind: Secret
metadata:
  name: krkn-operator-jwt-secret
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    krkn.krkn-chaos.dev/component: auth
type: Opaque
data:
  {{- if .Values.auth.jwtSecret }}
  jwt-secret: {{ .Values.auth.jwtSecret }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
