apiVersion: krkn-chaos.krkn-chaos.dev/v1alpha1
kind: KrknTarget
metadata:
  labels:
    app.kubernetes.io/name: krkn-operator
    app.kubernetes.io/managed-by: kustomize
  name: krkntarget-sample
spec:
  
