//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterJobStatus) DeepCopyInto(out *ClusterJobStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.LastRetryTime != nil {
		in, out := &in.LastRetryTime, &out.LastRetryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterJobStatus.
func (in *ClusterJobStatus) DeepCopy() *ClusterJobStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPermissionSet) DeepCopyInto(out *ClusterPermissionSet) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPermissionSet.
func (in *ClusterPermissionSet) DeepCopy() *ClusterPermissionSet {
	if in == nil {
		return nil
	}
	out := new(ClusterPermissionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResiliencyScore) DeepCopyInto(out *ClusterResiliencyScore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResiliencyScore.
func (in *ClusterResiliencyScore) DeepCopy() *ClusterResiliencyScore {
	if in == nil {
		return nil
	}
	out := new(ClusterResiliencyScore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTarget) DeepCopyInto(out *ClusterTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTarget.
func (in *ClusterTarget) DeepCopy() *ClusterTarget {
	if in == nil {
		return nil
	}
	out := new(ClusterTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileMount) DeepCopyInto(out *FileMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileMount.
func (in *FileMount) DeepCopy() *FileMount {
	if in == nil {
		return nil
	}
	out := new(FileMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphClusterScore) DeepCopyInto(out *GraphClusterScore) {
	*out = *in
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(float64)
		**out = **in
	}
	if in.NodeContributions != nil {
		in, out := &in.NodeContributions, &out.NodeContributions
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphClusterScore.
func (in *GraphClusterScore) DeepCopy() *GraphClusterScore {
	if in == nil {
		return nil
	}
	out := new(GraphClusterScore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphRunSummary) DeepCopyInto(out *GraphRunSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphRunSummary.
func (in *GraphRunSummary) DeepCopy() *GraphRunSummary {
	if in == nil {
		return nil
	}
	out := new(GraphRunSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphScenario) DeepCopyInto(out *GraphScenario) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphScenario.
func (in *GraphScenario) DeepCopy() *GraphScenario {
	if in == nil {
		return nil
	}
	out := new(GraphScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphScenarioNode) DeepCopyInto(out *GraphScenarioNode) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphScenarioNode.
func (in *GraphScenarioNode) DeepCopy() *GraphScenarioNode {
	if in == nil {
		return nil
	}
	out := new(GraphScenarioNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknFileType) DeepCopyInto(out *KrknFileType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknFileType.
func (in *KrknFileType) DeepCopy() *KrknFileType {
	if in == nil {
		return nil
	}
	out := new(KrknFileType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknFileType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknFileTypeList) DeepCopyInto(out *KrknFileTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknFileType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknFileTypeList.
func (in *KrknFileTypeList) DeepCopy() *KrknFileTypeList {
	if in == nil {
		return nil
	}
	out := new(KrknFileTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknFileTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknFileTypeSpec) DeepCopyInto(out *KrknFileTypeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknFileTypeSpec.
func (in *KrknFileTypeSpec) DeepCopy() *KrknFileTypeSpec {
	if in == nil {
		return nil
	}
	out := new(KrknFileTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknGraphRun) DeepCopyInto(out *KrknGraphRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknGraphRun.
func (in *KrknGraphRun) DeepCopy() *KrknGraphRun {
	if in == nil {
		return nil
	}
	out := new(KrknGraphRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknGraphRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknGraphRunList) DeepCopyInto(out *KrknGraphRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknGraphRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknGraphRunList.
func (in *KrknGraphRunList) DeepCopy() *KrknGraphRunList {
	if in == nil {
		return nil
	}
	out := new(KrknGraphRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknGraphRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknGraphRunSpec) DeepCopyInto(out *KrknGraphRunSpec) {
	*out = *in
	if in.Graph != nil {
		in, out := &in.Graph, &out.Graph
		*out = make(map[string]GraphScenarioNode, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.ResiliencyScoreBaseline != nil {
		in, out := &in.ResiliencyScoreBaseline, &out.ResiliencyScoreBaseline
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknGraphRunSpec.
func (in *KrknGraphRunSpec) DeepCopy() *KrknGraphRunSpec {
	if in == nil {
		return nil
	}
	out := new(KrknGraphRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknGraphRunStatus) DeepCopyInto(out *KrknGraphRunStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	out.Summary = in.Summary
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedLevels != nil {
		in, out := &in.ResolvedLevels, &out.ResolvedLevels
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.ResiliencyScores != nil {
		in, out := &in.ResiliencyScores, &out.ResiliencyScores
		*out = make([]GraphClusterScore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknGraphRunStatus.
func (in *KrknGraphRunStatus) DeepCopy() *KrknGraphRunStatus {
	if in == nil {
		return nil
	}
	out := new(KrknGraphRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTarget) DeepCopyInto(out *KrknOperatorTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTarget.
func (in *KrknOperatorTarget) DeepCopy() *KrknOperatorTarget {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetList) DeepCopyInto(out *KrknOperatorTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknOperatorTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetList.
func (in *KrknOperatorTargetList) DeepCopy() *KrknOperatorTargetList {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProvider) DeepCopyInto(out *KrknOperatorTargetProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProvider.
func (in *KrknOperatorTargetProvider) DeepCopy() *KrknOperatorTargetProvider {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderConfig) DeepCopyInto(out *KrknOperatorTargetProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderConfig.
func (in *KrknOperatorTargetProviderConfig) DeepCopy() *KrknOperatorTargetProviderConfig {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderConfigList) DeepCopyInto(out *KrknOperatorTargetProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknOperatorTargetProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderConfigList.
func (in *KrknOperatorTargetProviderConfigList) DeepCopy() *KrknOperatorTargetProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderConfigSpec) DeepCopyInto(out *KrknOperatorTargetProviderConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderConfigSpec.
func (in *KrknOperatorTargetProviderConfigSpec) DeepCopy() *KrknOperatorTargetProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderConfigStatus) DeepCopyInto(out *KrknOperatorTargetProviderConfigStatus) {
	*out = *in
	if in.ConfigData != nil {
		in, out := &in.ConfigData, &out.ConfigData
		*out = make(map[string]ProviderConfigData, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderConfigStatus.
func (in *KrknOperatorTargetProviderConfigStatus) DeepCopy() *KrknOperatorTargetProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderList) DeepCopyInto(out *KrknOperatorTargetProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknOperatorTargetProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderList.
func (in *KrknOperatorTargetProviderList) DeepCopy() *KrknOperatorTargetProviderList {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknOperatorTargetProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderSpec) DeepCopyInto(out *KrknOperatorTargetProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderSpec.
func (in *KrknOperatorTargetProviderSpec) DeepCopy() *KrknOperatorTargetProviderSpec {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetProviderStatus) DeepCopyInto(out *KrknOperatorTargetProviderStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetProviderStatus.
func (in *KrknOperatorTargetProviderStatus) DeepCopy() *KrknOperatorTargetProviderStatus {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetSpec) DeepCopyInto(out *KrknOperatorTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetSpec.
func (in *KrknOperatorTargetSpec) DeepCopy() *KrknOperatorTargetSpec {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknOperatorTargetStatus) DeepCopyInto(out *KrknOperatorTargetStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknOperatorTargetStatus.
func (in *KrknOperatorTargetStatus) DeepCopy() *KrknOperatorTargetStatus {
	if in == nil {
		return nil
	}
	out := new(KrknOperatorTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknScenarioRun) DeepCopyInto(out *KrknScenarioRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknScenarioRun.
func (in *KrknScenarioRun) DeepCopy() *KrknScenarioRun {
	if in == nil {
		return nil
	}
	out := new(KrknScenarioRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknScenarioRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknScenarioRunList) DeepCopyInto(out *KrknScenarioRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknScenarioRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknScenarioRunList.
func (in *KrknScenarioRunList) DeepCopy() *KrknScenarioRunList {
	if in == nil {
		return nil
	}
	out := new(KrknScenarioRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknScenarioRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknScenarioRunSpec) DeepCopyInto(out *KrknScenarioRunSpec) {
	*out = *in
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]FileMount, len(*in))
		copy(*out, *in)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknScenarioRunSpec.
func (in *KrknScenarioRunSpec) DeepCopy() *KrknScenarioRunSpec {
	if in == nil {
		return nil
	}
	out := new(KrknScenarioRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknScenarioRunStatus) DeepCopyInto(out *KrknScenarioRunStatus) {
	*out = *in
	if in.ClusterJobs != nil {
		in, out := &in.ClusterJobs, &out.ClusterJobs
		*out = make([]ClusterJobStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResiliencyScores != nil {
		in, out := &in.ResiliencyScores, &out.ResiliencyScores
		*out = make([]ClusterResiliencyScore, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknScenarioRunStatus.
func (in *KrknScenarioRunStatus) DeepCopy() *KrknScenarioRunStatus {
	if in == nil {
		return nil
	}
	out := new(KrknScenarioRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequest) DeepCopyInto(out *KrknTargetRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequest.
func (in *KrknTargetRequest) DeepCopy() *KrknTargetRequest {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknTargetRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestList) DeepCopyInto(out *KrknTargetRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknTargetRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestList.
func (in *KrknTargetRequestList) DeepCopy() *KrknTargetRequestList {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknTargetRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestSpec) DeepCopyInto(out *KrknTargetRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestSpec.
func (in *KrknTargetRequestSpec) DeepCopy() *KrknTargetRequestSpec {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknTargetRequestStatus) DeepCopyInto(out *KrknTargetRequestStatus) {
	*out = *in
	if in.TargetData != nil {
		in, out := &in.TargetData, &out.TargetData
		*out = make(map[string][]ClusterTarget, len(*in))
		for key, val := range *in {
			var outVal []ClusterTarget
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]ClusterTarget, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknTargetRequestStatus.
func (in *KrknTargetRequestStatus) DeepCopy() *KrknTargetRequestStatus {
	if in == nil {
		return nil
	}
	out := new(KrknTargetRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUser) DeepCopyInto(out *KrknUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUser.
func (in *KrknUser) DeepCopy() *KrknUser {
	if in == nil {
		return nil
	}
	out := new(KrknUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserGroup) DeepCopyInto(out *KrknUserGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserGroup.
func (in *KrknUserGroup) DeepCopy() *KrknUserGroup {
	if in == nil {
		return nil
	}
	out := new(KrknUserGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknUserGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserGroupList) DeepCopyInto(out *KrknUserGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknUserGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserGroupList.
func (in *KrknUserGroupList) DeepCopy() *KrknUserGroupList {
	if in == nil {
		return nil
	}
	out := new(KrknUserGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknUserGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserGroupSpec) DeepCopyInto(out *KrknUserGroupSpec) {
	*out = *in
	if in.ClusterPermissions != nil {
		in, out := &in.ClusterPermissions, &out.ClusterPermissions
		*out = make(map[string]ClusterPermissionSet, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserGroupSpec.
func (in *KrknUserGroupSpec) DeepCopy() *KrknUserGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KrknUserGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserList) DeepCopyInto(out *KrknUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KrknUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserList.
func (in *KrknUserList) DeepCopy() *KrknUserList {
	if in == nil {
		return nil
	}
	out := new(KrknUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KrknUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserSpec) DeepCopyInto(out *KrknUserSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserSpec.
func (in *KrknUserSpec) DeepCopy() *KrknUserSpec {
	if in == nil {
		return nil
	}
	out := new(KrknUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrknUserStatus) DeepCopyInto(out *KrknUserStatus) {
	*out = *in
	in.Created.DeepCopyInto(&out.Created)
	in.LastLogin.DeepCopyInto(&out.LastLogin)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrknUserStatus.
func (in *KrknUserStatus) DeepCopy() *KrknUserStatus {
	if in == nil {
		return nil
	}
	out := new(KrknUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigData) DeepCopyInto(out *ProviderConfigData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigData.
func (in *ProviderConfigData) DeepCopy() *ProviderConfigData {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigData)
	in.DeepCopyInto(out)
	return out
}
