#!/usr/bin/env bash
set -euo pipefail

# Prepare a rendered Kubernetes bundle, update a configured fork of the
# upstream community-operators catalog, and open the corresponding PR.

usage() {
  echo "usage: $0 <version> <rendered-kubernetes-bundle>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version=$1
bundle_dir=$2
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source "$script_dir/catalog-submit.sh"

[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
  echo "invalid release version: $version" >&2
  exit 2
}
[[ -d "$bundle_dir/manifests" && -f "$bundle_dir/metadata/annotations.yaml" ]] || {
  echo "rendered Kubernetes bundle is incomplete: $bundle_dir" >&2
  exit 1
}

csv_file=$(find "$bundle_dir/manifests" -maxdepth 1 -type f \
  -name '*.clusterserviceversion.yaml' -print -quit)
[[ -n "$csv_file" ]] || {
  echo "bundle does not contain a ClusterServiceVersion manifest" >&2
  exit 1
}

: "${KUBERNETES_OPERATORS_FORK:?KUBERNETES_OPERATORS_FORK must be configured (for example, <owner>/community-operators)}"
: "${GH_TOKEN:?GH_TOKEN must be configured with permission to push to KUBERNETES_OPERATORS_FORK and open upstream PRs}"

catalog_repository=${KUBERNETES_OPERATORS_REPOSITORY:-k8s-operatorhub/community-operators}

catalog_submit_checkout "$KUBERNETES_OPERATORS_FORK" "$catalog_repository" \
  "automation/krkn-operator-$version"
trap 'rm -rf "$CATALOG_WORK_DIR"' EXIT

package_dir="$CATALOG_DIR/operators/krkn-operator"
version_dir="$package_dir/$version"
[[ ! -e "$version_dir" ]] || {
  echo "catalog version already exists: operators/krkn-operator/$version" >&2
  exit 1
}

mkdir -p "$version_dir"
cp -R "$bundle_dir/manifests" "$version_dir/manifests"
cp -R "$bundle_dir/metadata" "$version_dir/metadata"

body_file="$CATALOG_WORK_DIR/pr-body.md"
cat > "$body_file" <<EOF
## Summary

This submission adds the krkn-operator Kubernetes bundle $version to OperatorHub.io.

The bundle and manifests were generated by the Krkn Operator release workflow.
The CSV includes human-readable display names, descriptions, and examples for all
owned custom resources.

## Release

- Source release: https://github.com/krkn-chaos/krkn-operator/releases/tag/v$version
- Operator image: https://quay.io/repository/krkn-chaos/krkn-operator?tag=v$version
EOF

catalog_submit_open_pr \
  "operators/krkn-operator/$version" \
  "operator: update krkn-operator bundle to $version" \
  "operator krkn-operator ($version)" \
  "$body_file"
