#!/usr/bin/env bash
set -euo pipefail

# Prepare a rendered OCP bundle, update the configured community-operators fork,
# and open the corresponding upstream catalog pull request. Requires GH_TOKEN
# and COMMUNITY_OPERATORS_FORK in the environment.

usage() {
  echo "usage: $0 <version> <rendered-ocp-bundle>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version=$1
bundle_dir=$2
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
source "$script_dir/release-channel.sh"
source "$script_dir/catalog-channel.sh"
source "$script_dir/catalog-submit.sh"
channel_name=$(release_channel_for_version stable-ocp "$version")

[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
  echo "invalid release version: $version" >&2
  exit 2
}
[[ -d "$bundle_dir/manifests" && -f "$bundle_dir/metadata/annotations.yaml" ]] || {
  echo "rendered OCP bundle is incomplete: $bundle_dir" >&2
  exit 1
}

csv_file=$(find "$bundle_dir/manifests" -maxdepth 1 -type f \
  -name '*.clusterserviceversion.yaml' -print -quit)
[[ -n "$csv_file" ]] || {
  echo "bundle does not contain a ClusterServiceVersion manifest" >&2
  exit 1
}

: "${COMMUNITY_OPERATORS_FORK:?COMMUNITY_OPERATORS_FORK must be configured (for example, <owner>/community-operators-prod)}"
: "${GH_TOKEN:?GH_TOKEN must be configured with permission to push to COMMUNITY_OPERATORS_FORK and open upstream PRs}"

catalog_repository=${COMMUNITY_OPERATORS_REPOSITORY:-redhat-openshift-ecosystem/community-operators-prod}

catalog_submit_checkout "$COMMUNITY_OPERATORS_FORK" "$catalog_repository" \
  "automation/krkn-operator-$version"
trap 'rm -rf "$CATALOG_WORK_DIR"' EXIT

package_dir="$CATALOG_DIR/operators/krkn-operator"
version_dir="$package_dir/$version"
[[ ! -e "$version_dir" ]] || {
  echo "catalog version already exists: operators/krkn-operator/$version" >&2
  exit 1
}

catalog_template="$package_dir/catalog-templates/basic.yaml"
[[ -f "$catalog_template" ]] || {
  echo "operator catalog template not found: $catalog_template" >&2
  exit 1
}

ensure_catalog_channel "$catalog_template" krkn-operator "$channel_name"
previous_bundle=""
if channel_has_entries "$catalog_template" krkn-operator "$channel_name"; then
  previous_bundle=$(bash "$script_dir/channel-head.sh" "$catalog_template" krkn-operator "$channel_name")
  [[ "$previous_bundle" =~ ^krkn-operator\.v[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
    echo "unable to determine the previous $channel_name bundle from $catalog_template: $previous_bundle" >&2
    exit 1
  }
fi
if [[ "$channel_name" != stable-ocp && "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  update_default_channel "$catalog_template" krkn-operator "$channel_name"
fi

mkdir -p "$version_dir"
cp -R "$bundle_dir/manifests" "$version_dir/manifests"
cp -R "$bundle_dir/metadata" "$version_dir/metadata"

icon_base64=$(yq -r '.spec.icon[0].base64data // ""' "$csv_file")
icon_mediatype=$(yq -r '.spec.icon[0].mediatype // ""' "$csv_file")
[[ -n "$icon_base64" && -n "$icon_mediatype" ]] || {
  echo "bundle CSV does not contain spec.icon" >&2
  exit 1
}

export ICON_BASE64="$icon_base64"
export ICON_MEDIATYPE="$icon_mediatype"

package_entries=$(yq -r \
  '[.entries[] | select(.schema == "olm.package" and .name == "krkn-operator")] | length' \
  "$catalog_template")
[[ "$package_entries" == "1" ]] || {
  echo "expected exactly one krkn-operator olm.package entry in $catalog_template, found $package_entries" >&2
  exit 1
}

yq -i \
  '(.entries[] | select(.schema == "olm.package" and .name == "krkn-operator") | .icon) = {
     "base64data": strenv(ICON_BASE64),
     "mediatype": strenv(ICON_MEDIATYPE)
   }' \
  "$catalog_template"

[[ "$(yq -r \
  '.entries[] | select(.schema == "olm.package" and .name == "krkn-operator") | .icon.mediatype // ""' \
  "$catalog_template")" == "$icon_mediatype" ]] || {
  echo "failed to update package icon in $catalog_template" >&2
  exit 1
}

write_release_config "$version_dir" "$channel_name" "$previous_bundle"

body_file="$CATALOG_WORK_DIR/pr-body.md"
cat > "$body_file" <<EOF
## Summary

This submission adds the krkn-operator bundle $version.

The bundle and catalog manifests were generated by the Krkn Operator release workflow.
The catalog package metadata also carries the operator icon so it is available to
the OpenShift Software Catalog tile.
The included release-config.yaml enables FBC autorelease for the $channel_name channel.
## Release

- Source release: https://github.com/krkn-chaos/krkn-operator/releases/tag/v$version
- Operator image: https://quay.io/repository/krkn-chaos/krkn-operator?tag=v$version
EOF

catalog_submit_open_pr \
  "operator: update krkn-operator bundle to $version" \
  "operator krkn-operator ($version)" \
  "$body_file" \
  "operators/krkn-operator/$version" \
  "$catalog_template"
