#!/usr/bin/env bash
set -euo pipefail

# Prepare a rendered Kubernetes bundle, update a configured fork of the
# upstream community-operators catalog, and open the corresponding PR.

usage() {
  echo "usage: $0 <version> <rendered-kubernetes-bundle>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version=$1
bundle_dir=$2

[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
  echo "invalid release version: $version" >&2
  exit 2
}
[[ -d "$bundle_dir/manifests" && -f "$bundle_dir/metadata/annotations.yaml" ]] || {
  echo "rendered Kubernetes bundle is incomplete: $bundle_dir" >&2
  exit 1
}

: "${KUBERNETES_OPERATORS_FORK:?KUBERNETES_OPERATORS_FORK must be configured (for example, <owner>/community-operators)}"
: "${GH_TOKEN:?GH_TOKEN must be configured with permission to push to KUBERNETES_OPERATORS_FORK and open upstream PRs}"

catalog_repository=${KUBERNETES_OPERATORS_REPOSITORY:-k8s-operatorhub/community-operators}
fork_owner=${KUBERNETES_OPERATORS_FORK%%/*}
[[ "$KUBERNETES_OPERATORS_FORK" == */* && -n "$fork_owner" ]] || {
  echo "KUBERNETES_OPERATORS_FORK must have the form <owner>/<repository>" >&2
  exit 2
}

git config --global user.name "github-actions[bot]"
git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
gh auth setup-git

work_dir=$(mktemp -d "${RUNNER_TEMP:-${TMPDIR:-/tmp}}/kubernetes-community-operators.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT

gh repo clone "$KUBERNETES_OPERATORS_FORK" "$work_dir/catalog" >/dev/null
if git -C "$work_dir/catalog" remote get-url upstream >/dev/null 2>&1; then
  git -C "$work_dir/catalog" remote set-url upstream "https://github.com/$catalog_repository.git"
else
  git -C "$work_dir/catalog" remote add upstream "https://github.com/$catalog_repository.git"
fi
git -C "$work_dir/catalog" remote set-url origin "https://github.com/$KUBERNETES_OPERATORS_FORK.git"
git -C "$work_dir/catalog" fetch --quiet upstream main
git -C "$work_dir/catalog" checkout --quiet -B "automation/krkn-operator-$version" upstream/main

package_dir="$work_dir/catalog/operators/krkn-operator"
version_dir="$package_dir/$version"
[[ ! -e "$version_dir" ]] || {
  echo "catalog version already exists: operators/krkn-operator/$version" >&2
  exit 1
}

mkdir -p "$version_dir"
cp -R "$bundle_dir/manifests" "$version_dir/manifests"
cp -R "$bundle_dir/metadata" "$version_dir/metadata"

git -C "$work_dir/catalog" add "operators/krkn-operator/$version"
git -C "$work_dir/catalog" commit -m "operator: update krkn-operator bundle to $version"
git -C "$work_dir/catalog" push --force-with-lease origin "automation/krkn-operator-$version"

existing_pr=$(gh pr list \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/krkn-operator-$version" \
  --state open \
  --json number \
  --jq '.[0].number // empty')
if [[ -n "$existing_pr" ]]; then
  echo "Updated existing catalog PR #$existing_pr"
  exit 0
fi

body_file="$work_dir/pr-body.md"
cat > "$body_file" <<EOF
## Summary

This submission adds the krkn-operator Kubernetes bundle $version to OperatorHub.io.

The bundle and manifests were generated by the Krkn Operator release workflow.
The CSV includes human-readable display names, descriptions, and examples for all
owned custom resources.

## Release

- Source release: https://github.com/krkn-chaos/krkn-operator/releases/tag/v$version
- Operator image: https://quay.io/repository/krkn-chaos/krkn-operator?tag=v$version
EOF

gh pr create \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/krkn-operator-$version" \
  --base main \
  --title "operator krkn-operator ($version)" \
  --body-file "$body_file"
