#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 <version> <rendered-ocp-bundle>" >&2
  exit 2
}

[[ $# -eq 2 ]] || usage
version=$1
bundle_dir=$2

[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$ ]] || {
  echo "invalid release version: $version" >&2
  exit 2
}
[[ -d "$bundle_dir/manifests" && -f "$bundle_dir/metadata/annotations.yaml" ]] || {
  echo "rendered OCP bundle is incomplete: $bundle_dir" >&2
  exit 1
}

: "${COMMUNITY_OPERATORS_FORK:?COMMUNITY_OPERATORS_FORK must be configured (for example, <owner>/community-operators-prod)}"
: "${GH_TOKEN:?GH_TOKEN must be configured with permission to push to COMMUNITY_OPERATORS_FORK and open upstream PRs}"

catalog_repository=${COMMUNITY_OPERATORS_REPOSITORY:-redhat-openshift-ecosystem/community-operators-prod}
fork_owner=${COMMUNITY_OPERATORS_FORK%%/*}
[[ "$COMMUNITY_OPERATORS_FORK" == */* && -n "$fork_owner" ]] || {
  echo "COMMUNITY_OPERATORS_FORK must have the form <owner>/<repository>" >&2
  exit 2
}

work_dir=$(mktemp -d "${RUNNER_TEMP:-${TMPDIR:-/tmp}}/community-operators.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT

gh repo clone "$COMMUNITY_OPERATORS_FORK" "$work_dir/catalog" >/dev/null
git -C "$work_dir/catalog" remote add upstream "https://github.com/$catalog_repository.git"
git -C "$work_dir/catalog" fetch --quiet upstream main
git -C "$work_dir/catalog" checkout --quiet -B "automation/krkn-operator-$version" upstream/main

package_dir="$work_dir/catalog/operators/krkn-operator"
version_dir="$package_dir/$version"
[[ ! -e "$version_dir" ]] || {
  echo "catalog version already exists: operators/krkn-operator/$version" >&2
  exit 1
}

previous_version=$(find "$package_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort -V | tail -n 1)
[[ -n "$previous_version" ]] || {
  echo "unable to determine the previous krkn-operator catalog version" >&2
  exit 1
}

mkdir -p "$version_dir"
cp -R "$bundle_dir/manifests" "$version_dir/manifests"
cp -R "$bundle_dir/metadata" "$version_dir/metadata"

catalog_template="$work_dir/catalog/catalog-templates/basic.yaml"
[[ -f "$catalog_template" ]] || {
  echo "catalog template not found: catalog-templates/basic.yaml" >&2
  exit 1
}

csv_file=$(find "$bundle_dir/manifests" -maxdepth 1 -type f \
  -name '*.clusterserviceversion.yaml' -print -quit)
[[ -n "$csv_file" ]] || {
  echo "bundle does not contain a ClusterServiceVersion manifest" >&2
  exit 1
}

icon_base64=$(yq -r '.spec.icon[0].base64data // ""' "$csv_file")
icon_mediatype=$(yq -r '.spec.icon[0].mediatype // ""' "$csv_file")
[[ -n "$icon_base64" && -n "$icon_mediatype" ]] || {
  echo "bundle CSV does not contain spec.icon" >&2
  exit 1
}

package_entries=$(yq -r '[.entries[] | select(.schema == "olm.package" and .name == "krkn-operator")] | length' "$catalog_template")
[[ "$package_entries" == "1" ]] || {
  echo "expected exactly one krkn-operator olm.package entry in $catalog_template, found $package_entries" >&2
  exit 1
}

export ICON_BASE64="$icon_base64"
export ICON_MEDIATYPE="$icon_mediatype"
yq -i \
  '(.entries[] | select(.schema == "olm.package" and .name == "krkn-operator") | .icon) = {
     "base64data": strenv(ICON_BASE64),
     "mediatype": strenv(ICON_MEDIATYPE)
   }' \
  "$catalog_template"

cat > "$version_dir/release-config.yaml" <<EOF
---
catalog_templates:
  - template_name: basic.yaml
    channels:
      - stable-ocp
    replaces: krkn-operator.v$previous_version
EOF

git -C "$work_dir/catalog" add "operators/krkn-operator/$version" "$catalog_template"
git -C "$work_dir/catalog" commit -m "operator: update krkn-operator bundle to $version"
git -C "$work_dir/catalog" push --force-with-lease origin "automation/krkn-operator-$version"

existing_pr=$(gh pr list \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/krkn-operator-$version" \
  --state open \
  --json number \
  --jq '.[0].number // empty')
if [[ -n "$existing_pr" ]]; then
  echo "Updated existing catalog PR #$existing_pr"
  exit 0
fi

body_file="$work_dir/pr-body.md"
cat > "$body_file" <<EOF
## Summary

This submission adds the krkn-operator bundle $version.

The bundle and catalog manifests were generated by the Krkn Operator release workflow.
The catalog package metadata also carries the operator icon so it is available to
the OpenShift Software Catalog tile.
The included release-config.yaml enables FBC autorelease for the stable-ocp channel,
replacing krkn-operator.v$previous_version.

## Release

- Source release: https://github.com/krkn-chaos/krkn-operator/releases/tag/v$version
- Operator image: https://quay.io/repository/krkn-chaos/krkn-operator?tag=v$version
EOF

gh pr create \
  --repo "$catalog_repository" \
  --head "$fork_owner:automation/krkn-operator-$version" \
  --base main \
  --title "operator krkn-operator ($version)" \
  --body-file "$body_file"
