// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: dataprovider.proto

package dataprovider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetNodesRequest contains the kubeconfig to access the cluster
type GetNodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kubeconfig in base64 format
	KubeconfigBase64 string `protobuf:"bytes,1,opt,name=kubeconfig_base64,json=kubeconfigBase64,proto3" json:"kubeconfig_base64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_dataprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_dataprovider_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodesRequest) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

// GetNodesResponse contains the list of node names
type GetNodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of node names
	Nodes         []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_dataprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_dataprovider_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_dataprovider_proto protoreflect.FileDescriptor

const file_dataprovider_proto_rawDesc = "" +
	"\n" +
	"\x12dataprovider.proto\x12\fdataprovider\">\n" +
	"\x0fGetNodesRequest\x12+\n" +
	"\x11kubeconfig_base64\x18\x01 \x01(\tR\x10kubeconfigBase64\"(\n" +
	"\x10GetNodesResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes2`\n" +
	"\x13DataProviderService\x12I\n" +
	"\bGetNodes\x12\x1d.dataprovider.GetNodesRequest\x1a\x1e.dataprovider.GetNodesResponseB8Z6github.com/krkn-chaos/krkn-operator/proto/dataproviderb\x06proto3"

var (
	file_dataprovider_proto_rawDescOnce sync.Once
	file_dataprovider_proto_rawDescData []byte
)

func file_dataprovider_proto_rawDescGZIP() []byte {
	file_dataprovider_proto_rawDescOnce.Do(func() {
		file_dataprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataprovider_proto_rawDesc), len(file_dataprovider_proto_rawDesc)))
	})
	return file_dataprovider_proto_rawDescData
}

var file_dataprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dataprovider_proto_goTypes = []any{
	(*GetNodesRequest)(nil),  // 0: dataprovider.GetNodesRequest
	(*GetNodesResponse)(nil), // 1: dataprovider.GetNodesResponse
}
var file_dataprovider_proto_depIdxs = []int32{
	0, // 0: dataprovider.DataProviderService.GetNodes:input_type -> dataprovider.GetNodesRequest
	1, // 1: dataprovider.DataProviderService.GetNodes:output_type -> dataprovider.GetNodesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dataprovider_proto_init() }
func file_dataprovider_proto_init() {
	if File_dataprovider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataprovider_proto_rawDesc), len(file_dataprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataprovider_proto_goTypes,
		DependencyIndexes: file_dataprovider_proto_depIdxs,
		MessageInfos:      file_dataprovider_proto_msgTypes,
	}.Build()
	File_dataprovider_proto = out.File
	file_dataprovider_proto_goTypes = nil
	file_dataprovider_proto_depIdxs = nil
}
