// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/dataprovider.proto

package dataprovider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetNodesRequest contains the kubeconfig to access the cluster
type GetNodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kubeconfig in base64 format
	KubeconfigBase64 string `protobuf:"bytes,1,opt,name=kubeconfig_base64,json=kubeconfigBase64,proto3" json:"kubeconfig_base64,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_proto_dataprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataprovider_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodesRequest) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

// GetNodesResponse contains the list of node names
type GetNodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of node names
	Nodes         []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_proto_dataprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataprovider_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodesResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// ExecuteKubectlRequest contains the command to execute and authentication
type ExecuteKubectlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kubeconfig in base64 format
	KubeconfigBase64 string `protobuf:"bytes,1,opt,name=kubeconfig_base64,json=kubeconfigBase64,proto3" json:"kubeconfig_base64,omitempty"`
	// command to execute (kubectl or oc)
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// subcommand (e.g., get, describe, logs)
	Subcommand string `protobuf:"bytes,3,opt,name=subcommand,proto3" json:"subcommand,omitempty"`
	// positional arguments (e.g., pods, nginx, default)
	Args []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// named flags with values (e.g., namespace: default, output: yaml)
	Flags map[string]string `protobuf:"bytes,5,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// boolean flags without values (e.g., all-namespaces, show-labels)
	BooleanFlags []string `protobuf:"bytes,6,rep,name=boolean_flags,json=booleanFlags,proto3" json:"boolean_flags,omitempty"`
	// timeout in seconds (default: 120)
	TimeoutSeconds int32 `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteKubectlRequest) Reset() {
	*x = ExecuteKubectlRequest{}
	mi := &file_proto_dataprovider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteKubectlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteKubectlRequest) ProtoMessage() {}

func (x *ExecuteKubectlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataprovider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteKubectlRequest.ProtoReflect.Descriptor instead.
func (*ExecuteKubectlRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataprovider_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteKubectlRequest) GetKubeconfigBase64() string {
	if x != nil {
		return x.KubeconfigBase64
	}
	return ""
}

func (x *ExecuteKubectlRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteKubectlRequest) GetSubcommand() string {
	if x != nil {
		return x.Subcommand
	}
	return ""
}

func (x *ExecuteKubectlRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteKubectlRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ExecuteKubectlRequest) GetBooleanFlags() []string {
	if x != nil {
		return x.BooleanFlags
	}
	return nil
}

func (x *ExecuteKubectlRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// ExecuteKubectlResponse contains the command execution result
type ExecuteKubectlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stdout output in base64 format
	StdoutBase64 string `protobuf:"bytes,1,opt,name=stdout_base64,json=stdoutBase64,proto3" json:"stdout_base64,omitempty"`
	// stderr output in base64 format
	StderrBase64 string `protobuf:"bytes,2,opt,name=stderr_base64,json=stderrBase64,proto3" json:"stderr_base64,omitempty"`
	// command exit code (0 = success)
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error message if execution failed (not_found, not_permitted, execution_error, timeout)
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteKubectlResponse) Reset() {
	*x = ExecuteKubectlResponse{}
	mi := &file_proto_dataprovider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteKubectlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteKubectlResponse) ProtoMessage() {}

func (x *ExecuteKubectlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataprovider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteKubectlResponse.ProtoReflect.Descriptor instead.
func (*ExecuteKubectlResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataprovider_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteKubectlResponse) GetStdoutBase64() string {
	if x != nil {
		return x.StdoutBase64
	}
	return ""
}

func (x *ExecuteKubectlResponse) GetStderrBase64() string {
	if x != nil {
		return x.StderrBase64
	}
	return ""
}

func (x *ExecuteKubectlResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteKubectlResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_dataprovider_proto protoreflect.FileDescriptor

const file_proto_dataprovider_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dataprovider.proto\x12\fdataprovider\">\n" +
	"\x0fGetNodesRequest\x12+\n" +
	"\x11kubeconfig_base64\x18\x01 \x01(\tR\x10kubeconfigBase64\"(\n" +
	"\x10GetNodesResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\"\xe0\x02\n" +
	"\x15ExecuteKubectlRequest\x12+\n" +
	"\x11kubeconfig_base64\x18\x01 \x01(\tR\x10kubeconfigBase64\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1e\n" +
	"\n" +
	"subcommand\x18\x03 \x01(\tR\n" +
	"subcommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12D\n" +
	"\x05flags\x18\x05 \x03(\v2..dataprovider.ExecuteKubectlRequest.FlagsEntryR\x05flags\x12#\n" +
	"\rboolean_flags\x18\x06 \x03(\tR\fbooleanFlags\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x16ExecuteKubectlResponse\x12#\n" +
	"\rstdout_base64\x18\x01 \x01(\tR\fstdoutBase64\x12#\n" +
	"\rstderr_base64\x18\x02 \x01(\tR\fstderrBase64\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xbd\x01\n" +
	"\x13DataProviderService\x12I\n" +
	"\bGetNodes\x12\x1d.dataprovider.GetNodesRequest\x1a\x1e.dataprovider.GetNodesResponse\x12[\n" +
	"\x0eExecuteKubectl\x12#.dataprovider.ExecuteKubectlRequest\x1a$.dataprovider.ExecuteKubectlResponseB8Z6github.com/krkn-chaos/krkn-operator/proto/dataproviderb\x06proto3"

var (
	file_proto_dataprovider_proto_rawDescOnce sync.Once
	file_proto_dataprovider_proto_rawDescData []byte
)

func file_proto_dataprovider_proto_rawDescGZIP() []byte {
	file_proto_dataprovider_proto_rawDescOnce.Do(func() {
		file_proto_dataprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dataprovider_proto_rawDesc), len(file_proto_dataprovider_proto_rawDesc)))
	})
	return file_proto_dataprovider_proto_rawDescData
}

var file_proto_dataprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dataprovider_proto_goTypes = []any{
	(*GetNodesRequest)(nil),        // 0: dataprovider.GetNodesRequest
	(*GetNodesResponse)(nil),       // 1: dataprovider.GetNodesResponse
	(*ExecuteKubectlRequest)(nil),  // 2: dataprovider.ExecuteKubectlRequest
	(*ExecuteKubectlResponse)(nil), // 3: dataprovider.ExecuteKubectlResponse
	nil,                            // 4: dataprovider.ExecuteKubectlRequest.FlagsEntry
}
var file_proto_dataprovider_proto_depIdxs = []int32{
	4, // 0: dataprovider.ExecuteKubectlRequest.flags:type_name -> dataprovider.ExecuteKubectlRequest.FlagsEntry
	0, // 1: dataprovider.DataProviderService.GetNodes:input_type -> dataprovider.GetNodesRequest
	2, // 2: dataprovider.DataProviderService.ExecuteKubectl:input_type -> dataprovider.ExecuteKubectlRequest
	1, // 3: dataprovider.DataProviderService.GetNodes:output_type -> dataprovider.GetNodesResponse
	3, // 4: dataprovider.DataProviderService.ExecuteKubectl:output_type -> dataprovider.ExecuteKubectlResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dataprovider_proto_init() }
func file_proto_dataprovider_proto_init() {
	if File_proto_dataprovider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dataprovider_proto_rawDesc), len(file_proto_dataprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dataprovider_proto_goTypes,
		DependencyIndexes: file_proto_dataprovider_proto_depIdxs,
		MessageInfos:      file_proto_dataprovider_proto_msgTypes,
	}.Build()
	File_proto_dataprovider_proto = out.File
	file_proto_dataprovider_proto_goTypes = nil
	file_proto_dataprovider_proto_depIdxs = nil
}
