// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: dataprovider.proto

package dataprovider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataProviderService_GetNodes_FullMethodName = "/dataprovider.DataProviderService/GetNodes"
)

// DataProviderServiceClient is the client API for DataProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataProviderService provides methods to interact with Kubernetes clusters
type DataProviderServiceClient interface {
	// GetNodes retrieves the list of nodes from a Kubernetes cluster
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
}

type dataProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProviderServiceClient(cc grpc.ClientConnInterface) DataProviderServiceClient {
	return &dataProviderServiceClient{cc}
}

func (c *dataProviderServiceClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, DataProviderService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProviderServiceServer is the server API for DataProviderService service.
// All implementations must embed UnimplementedDataProviderServiceServer
// for forward compatibility.
//
// DataProviderService provides methods to interact with Kubernetes clusters
type DataProviderServiceServer interface {
	// GetNodes retrieves the list of nodes from a Kubernetes cluster
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	mustEmbedUnimplementedDataProviderServiceServer()
}

// UnimplementedDataProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataProviderServiceServer struct{}

func (UnimplementedDataProviderServiceServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedDataProviderServiceServer) mustEmbedUnimplementedDataProviderServiceServer() {}
func (UnimplementedDataProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeDataProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProviderServiceServer will
// result in compilation errors.
type UnsafeDataProviderServiceServer interface {
	mustEmbedUnimplementedDataProviderServiceServer()
}

func RegisterDataProviderServiceServer(s grpc.ServiceRegistrar, srv DataProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedDataProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataProviderService_ServiceDesc, srv)
}

func _DataProviderService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataProviderService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServiceServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataProviderService_ServiceDesc is the grpc.ServiceDesc for DataProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataprovider.DataProviderService",
	HandlerType: (*DataProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _DataProviderService_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataprovider.proto",
}
