{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krkn-operator.fullname" . }}-krkn-scenario-runner
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: scenario-runner
{{- end }}