{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krkn-operator.operator.fullname" . }}
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: {{ .Values.operator.service.type }}
  ports:
  - name: http
    port: {{ .Values.operator.service.port }}
    protocol: TCP
    targetPort: http
  - name: grpc
    port: {{ .Values.operator.service.grpcPort }}
    protocol: TCP
    targetPort: grpc
  selector:
    {{- include "krkn-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krkn-operator.operator.fullname" . }}-metrics
  namespace: {{ include "krkn-operator.namespace" . }}
  labels:
    {{- include "krkn-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    control-plane: controller-manager
  {{- with .Values.monitoring.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: {{ .Values.monitoring.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "krkn-operator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
{{- end }}
